version: "3.7"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: valoriza
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - valoriza-network
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: adminer
    tty: true
    ports:
      - 8080:8080
    networks:
      - valoriza-network

  valoriza:
    stdin_open: true
    image: node:16.14.2
    # command: npm run dev
    container_name: valoriza
    working_dir: /srv/valoriza/
    volumes:
      - .:/srv/valoriza
      # - valoriza_node_modules:/srv/valoriza/node_modules
    depends_on:
      - postgres
    ports:
      - 3333:3333
    networks:
      - valoriza-network

networks:
  valoriza-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  # valoriza_node_modules:
